// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_no_continues = "CgkI9-mD8LkCEAIQCw"; // <GPGSID>
        public const string achievement_perfect_streak_10 = "CgkI9-mD8LkCEAIQBQ"; // <GPGSID>
        public const string achievement_miniboss_assassin = "CgkI9-mD8LkCEAIQCA"; // <GPGSID>
        public const string achievement_beat_10_levels = "CgkI9-mD8LkCEAIQAw"; // <GPGSID>
        public const string achievement_beat_5_levels = "CgkI9-mD8LkCEAIQAg"; // <GPGSID>
        public const string achievement_perfect_streak_5 = "CgkI9-mD8LkCEAIQBA"; // <GPGSID>
        public const string achievement_play_100_games = "CgkI9-mD8LkCEAIQBw"; // <GPGSID>
        public const string achievement_heroic_actions = "CgkI9-mD8LkCEAIQCg"; // <GPGSID>
        public const string achievement_miniboss_terminator = "CgkI9-mD8LkCEAIQCQ"; // <GPGSID>
        public const string achievement_beat_1_level = "CgkI9-mD8LkCEAIQAQ"; // <GPGSID>
        public const string achievement_play_10_games = "CgkI9-mD8LkCEAIQBg"; // <GPGSID>

}

